# Generated by Django 5.2.8 on 2025-11-15 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Priority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('color', models.CharField(default='#000000', max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('execute_time', models.DateField()),
                ('icon', models.CharField(choices=[('fa-solid fa-flag', 'Flag'), ('fa-solid fa-circle-exclamation', 'Alert'), ('fa-solid fa-check', 'Check')], default='fa-solid fa-check', max_length=100)),
                ('priority', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.priority')),
            ],
        ),
    ]
