# Generated by Django 5.2.8 on 2025-11-15 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='icon',
        ),
        migrations.AddField(
            model_name='priority',
            name='icon',
            field=models.CharField(choices=[('fa-solid fa-flag', 'Flag'), ('fa-solid fa-circle-exclamation', 'Alert'), ('fa-solid fa-check', 'Check')], default='fa-solid fa-check', max_length=100),
        ),
    ]
