# Generated by Django 5.2.8 on 2025-11-15 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_event_icon_priority_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='BirthDayEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_name', models.CharField(max_length=150)),
                ('datetime', models.DateField()),
                ('priority', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.priority')),
            ],
        ),
    ]
